### ISSUE TITLE
Ruleset is not read by the editor leading to a NullReferenceException

### ISSUE THREAD

**Issue by Coppertine** [LeNitrous/sbtw#4]
Basically what said in title, it happens when ever I attmept to create a new project and / or load a created project.
This is done on develop branch with only a new switch case for the Exceptions on Editor.cs
Below is a stack trace.
```2022-01-13 16:50:43 [error]: An null error occured in the code.    at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods, CancellationToken token)
2022-01-13 16:50:43 [error]: at sbtw.Editor.Editor.generate[T,U](Generator`2 generator, GenerateTarget target, Boolean excludeNonVisible, CancellationToken token) in C:\Users\nick_\RiderProjects\sbtw\src\editor\sbtw.Editor\Editor.cs:line 334
2022-01-13 16:50:43 [error]: at sbtw.Editor.Editor.<GeneratePreview>b__24_0() in C:\Users\nick_\RiderProjects\sbtw\src\editor\sbtw.Editor\Editor.cs:line 215
2022-01-13 16:50:43 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2022-01-13 16:50:43 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods, CancellationToken token)
2022-01-13 16:50:43 [error]: at sbtw.Editor.Editor.generate[T,U](Generator`2 generator, GenerateTarget target, Boolean excludeNonVisible, CancellationToken token) in C:\Users\nick_\RiderProjects\sbtw\src\editor\sbtw.Editor\Editor.cs:line 334
2022-01-13 16:50:43 [error]: at sbtw.Editor.Editor.<GeneratePreview>b__24_0() in C:\Users\nick_\RiderProjects\sbtw\src\editor\sbtw.Editor\Editor.cs:line 215```

**Comment by LeNitrous** [comment]
From the looks of things, it seems that the beatmap has failed to load. Can you confirm that there is a `Beatmap` folder in the project you are trying to load?

**Comment by Coppertine** [comment]
This happens on creation of a new project. Yes, there is a `Beatmap` folder found.

**Comment by Coppertine** [comment]
Closing issue due to osu.Game.Rulesets.Osu version mismatch.

**Comment by LeNitrous** [comment]
Caused by a version mismatch in the project dependencies. Will close in the next push.
